name: "dbt_bigquery_monitoring"
version: "0.5.1"
require-dbt-version: [">=1.3.0", "<2.0.0"]
config-version: 2

profile: dbt_bigquery_monitoring

model-paths: ["models"]

clean-targets:
  - target
  - dbt_packages

models:
  +start: Jan 1 2017
  dbt_bigquery_monitoring:
    +tags:
      - "dbt-bigquery-monitoring"
    +on_schema_change: "append_new_columns"
    compute:
      +tags:
        - "dbt-bigquery-monitoring-compute"
    storage:
      +tags:
        - "dbt-bigquery-monitoring-storage"
    base:
      google:
        +materialized: "ephemeral"

vars:
  # Environment configuration
  bq_region: "{{ env_var('DBT_BQ_MONITORING_REGION', 'us') }}"
  input_gcp_projects: "{{ env_var('DBT_BQ_MONITORING_GCP_PROJECTS') }}" # example: ['my-gcp-project', 'my-gcp-project2']
  # https://cloud.google.com/bigquery/pricing#pricing
  # On-demand compute (analysis) pricing
  use_flat_pricing: "{{ env_var('DBT_BQ_MONITORING_USE_FLAT_PRICING', true) }}"
  per_billed_tb_price: "{{ env_var('DBT_BQ_MONITORING_PER_BILLED_TB_PRICE', 6.25) }}"
  free_tb_per_month: "{{ env_var('DBT_BQ_MONITORING_FREE_TB_PER_MONTH', 1) }}"
  # Capacity compute (analysis) pricing
  hourly_slot_price: "{{ env_var('DBT_BQ_MONITORING_HOURLY_SLOT_PRICE', 0.04) }}"
  # https://cloud.google.com/bigquery/pricing#storage
  prefer_physical_pricing_model: "{{ env_var('DBT_BQ_MONITORING_PREFER_PHYSICAL_PRICING_MODEL', true) }}"
  active_logical_storage_gb_price: "{{ env_var('DBT_BQ_MONITORING_ACTIVE_LOGICAL_STORAGE_GB_PRICE', 0.02) }}"
  long_term_logical_storage_gb_price: "{{ env_var('DBT_BQ_MONITORING_LONG_TERM_LOGICAL_STORAGE_GB_PRICE', 0.01) }}"
  active_physical_storage_gb_price: "{{ env_var('DBT_BQ_MONITORING_ACTIVE_PHYSICAL_STORAGE_GB_PRICE', 0.04) }}"
  long_term_physical_storage_gb_price: "{{ env_var('DBT_BQ_MONITORING_LONG_TERM_PHYSICAL_STORAGE_GB_PRICE', 0.02) }}"
  free_storage_gb_per_month: "{{ env_var('DBT_BQ_MONITORING_FREE_STORAGE_GB_PER_MONTH', 10) }}"

  # Project input configuration
  lookback_window_days: "{{ env_var('DBT_BQ_MONITORING_LOOKBACK_WINDOW_DAYS', 7) }}"
  # Project output configuration
  output_materialization: "{{ env_var('DBT_BQ_MONITORING_OUTPUT_MATERIALIZATION', 'table') }}"
  output_limit_size: "{{ env_var('DBT_BQ_MONITORING_OUTPUT_LIMIT_SIZE', 1000) }}"
