name: Generate Release PR

on:
  workflow_dispatch:

jobs:
  generate-pr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Batch changes
      uses: miniscruff/changie-action@v2
      with:
        version: latest
        args: batch auto

    - name: Merge changes
      uses: miniscruff/changie-action@v2
      with:
        version: latest
        args: merge

    - name: Get the latest version
      id: latest
      uses: miniscruff/changie-action@v2
      with:
        version: latest
        args: latest

    - name: Update README.md example to ${{ steps.latest.outputs.output }}
      run: |
        sed -i '' 's/version: [0-9]*\.[0-9]*\.[0-9]*/version: ${{ steps.latest.outputs.output }}/' README.md

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        title: Release ${{ steps.latest.outputs.output }}
        branch: release/${{ steps.latest.outputs.output }}
        commit-message: Release ${{ steps.latest.outputs.output }}
